version: '3'
services:
  namenode:
    build: ./namenode/
    ports:
      - "5000:5000"
    environment:
      - FRACTION_SIZE=10
      - PORT=5000
    networks:
      dfs_network:
        ipv4_address: 172.20.0.2
  # client:
  #   build: ./client/
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - FRACTION_SIZE=10
  #   networks:
  #     dfsnetwork:
  #       ipv4_address: 172.20.0.3
  datanode:
    build: ./datanode/
    depends_on:
      - namenode
    networks:
      dfs_network:
    scale: 4
networks:
  dfs_network:
    external:
      name: dfs_network