version: '3'
services:
  namenode:
    image: giansz/namenode:latest
    ports:
      - "5000:5000"
    environment:
      - FRACTION_SIZE=10
      - PORT=5000
    networks:
      dfs_network:
        ipv4_address: 172.20.0.2
  client:
    image: giansz/client:latest
    ports:
      - 8080:8080
    environment:
      - FRACTION_SIZE=10
      - SERVER_PORT=8080
      - NAMENODE_HOST=172.20.0.2
      - NAMENODE_PORT=5000
      - DATANODE_PORT=3000
    networks:
      dfs_network:
        ipv4_address: 172.20.0.3
  datanode:
    image: giansz/datanode:latest
    depends_on:
      - namenode
    environment:
      - GRPC_PORT=3000
      - NAMENODE_HOST=172.20.0.2
      - NAMENODE_PORT=5000
    networks:
      dfs_network:
    scale: 4
networks:
  dfs_network:
    external:
      name: dfs_network